### ISSUE TITLE
数据库

### ISSUE THREAD

**Issue by twosmi1e** [1m188/management_system#1]
大佬数据库文件没给呀，留个数据库结构也行呀

**Comment by 1m188** [comment]
数据库的话，在MySQL中建一个叫做stuinfosystem的数据库，其中有两张表，分别是acount和stuinfo。acount表中主要储存用户登陆的昵称和密码，有两个字段，分别是username和password，都是char类型，长度分别为100，100，都是not null。至于stuinfo表中则储存的是学生的信息，字段分别是name,age,num,profession，分别存储学生的姓名，年龄，学号和专业，类型分别为char，int，char，char，长度分别为10，11，20，50。如果要修改连接数据库的相关信息的话，需要在data.py中的init函数修改一下，差不多就这些。不过后面可能还会再改。现在这个代码是对应的这个数据库的表结构。

**Comment by 1m188** [comment]
现在可以查看readme文档了，其中有数据库的配置信息。

**Comment by twosmi1e** [comment]
好的谢谢大佬
